name: "Functional Test"
on: ["push"]

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: apt install
        run: sudo apt install -y fuse libfuse-dev libsqlite3-dev consul

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ inputs.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ inputs.os }}-go-

      - name: Start consul in dev mode
        run: consul agent -dev &

      - name: Run functional tests
        run: go test -v -p 1 -run=TestFunctional_OK ./cmd/litefs -funtime 30s
        timeout-minutes: 10
