on:
  release:
    types:
      - published
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches-ignore:
      - "dependabot/**"

name: "Pull Request"
jobs:
  docker:
    name: "Publish to Docker"
    runs-on: ubuntu-latest
    env:
      PLATFORMS: "linux/amd64"
      VERSION: "${{ github.event_name == 'release' && github.event.release.name || github.sha }}"

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: benbjohnson
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: flyio/litefs
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=sha,format=long
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            LITEFS_VERSION=${{ env.VERSION }}
